version: '3.7'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=flip#$%^flop
      - POSTGRES_USER=maryg

    volumes:
      - ./data:/var/lib/postgresql/data

    ports:
      - '5432:5432'