version: '3.7'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-hwpostgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Flip#$%^Flop}

    volumes:
      - ./data/postgres
    ports:
      - '5432:5432'

